com.example.fragmject.core.model.Article
com.example.fragmject.core.model.ArticleData
com.example.fragmject.core.model.ArticleTag
com.example.fragmject.core.model.Banner
com.example.fragmject.core.model.History
com.example.fragmject.core.model.HotKey
com.example.fragmject.core.model.NavTab
com.example.fragmject.core.model.ProjectTree
com.example.fragmject.core.model.User