{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.miaow",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 38269,
          "sha512": "889d30374c1e9769ce64e0c4ec32049f2c7dc291c999b929a0bc099dc18d8030040c0a3354ad5835f5d300877986d63c16f80e086af7b906eda3ab299867617b",
          "sha256": "956c131f20c462857e786c6cc4b51d1a769b684e3711b1e4b4165f84b05461dd",
          "sha1": "773b390558a5782427053c232e8abee35c4ddc9a",
          "md5": "01d11806f9cd66d9eaa580f74f27bb89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.2"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 38269,
          "sha512": "889d30374c1e9769ce64e0c4ec32049f2c7dc291c999b929a0bc099dc18d8030040c0a3354ad5835f5d300877986d63c16f80e086af7b906eda3ab299867617b",
          "sha256": "956c131f20c462857e786c6cc4b51d1a769b684e3711b1e4b4165f84b05461dd",
          "sha1": "773b390558a5782427053c232e8abee35c4ddc9a",
          "md5": "01d11806f9cd66d9eaa580f74f27bb89"
        }
      ]
    }
  ]
}
