{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.miaow",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 36143,
          "sha512": "da6489c781e05d154a7f508453f1aa094e192ac06fd26035027ea5e3997cee5485f7baf9ec1d9eb7a234f3fd120c902e3de653b448a187c98882959e4f4983b4",
          "sha256": "5939b393e90aab1dc27e065f3b4cb207b06fd4f1bac2f7124bd0517529086529",
          "sha1": "24b36ec365abf73fd0d7b15c50d2d5bc5a9b6ba8",
          "md5": "a9cc523a155eea9da5717211a80a03c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.0.0-rc01"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 36143,
          "sha512": "da6489c781e05d154a7f508453f1aa094e192ac06fd26035027ea5e3997cee5485f7baf9ec1d9eb7a234f3fd120c902e3de653b448a187c98882959e4f4983b4",
          "sha256": "5939b393e90aab1dc27e065f3b4cb207b06fd4f1bac2f7124bd0517529086529",
          "sha1": "24b36ec365abf73fd0d7b15c50d2d5bc5a9b6ba8",
          "md5": "a9cc523a155eea9da5717211a80a03c0"
        }
      ]
    }
  ]
}
